///  TO DO: BU UYGULAMADA BAZI WİDGET TARZLARININ İLK DENMELERİ YAPILMAKTA VE HALİHAZIRDA ÇALIŞAN
///  WİDGETLARIN KOD SATIRLARI DÜZENLİ BİR ŞEKİLE TUTULMAKTADIR.
///  İÇİNDE BULUNAN KOD SATIRLARI
///
///
/// NAV BAR - SİDEBAR - DRAWER
/// TİME PİCKER - CLOCK
/// DATE TİME PİCKER
///
///
///